apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: supertuxkart
  namespace: default
spec:
  replicas: 3

  template:
    metadata:
      labels:
        app: supertuxkart
    spec:
      ports:
        - name:          default
          portPolicy:    Dynamic
          containerPort: 8080
          protocol:      UDP

      health:
        initialDelaySeconds: 30
        periodSeconds:       5
        failureThreshold:    5

      template:
        spec:
          containers:
            - name:  supertuxkart
              image: us-docker.pkg.dev/agones-images/examples/supertuxkart-example:0.15

              resources:
                requests:
                  memory: "256Mi"
                  cpu:    "250m"
                limits:
                  memory: "512Mi"
                  cpu:    "500m"
